export const queryKeys = {
  clients: (params = {}) => ['clients', params],
  client: (clientId) => ['client', clientId],
  clientRelations: (clientId) => ['clientRelations', clientId],
  messengerSummary: ['messengerSummary'],
  calls: (params = {}) => ['calls', params],
  call: (callId) => ['call', callId],
  events: (params = {}) => ['events', params],
  event: (eventId) => ['event', eventId],
  transactions: (params = {}) => ['transactions', params],
  transactionsAll: ['transactions', {}],
  statistics: (params = {}) => ['statistics', params],
  services: (params = {}) => ['services', params],
  service: (serviceId) => ['service', serviceId],
  serviceGroups: (params = {}) => ['serviceGroups', params],
  serviceGroup: (serviceGroupId) => ['serviceGroup', serviceGroupId],
  users: (params = {}) => ['users', params],
  user: (userId) => ['user', userId],
  tariffs: (params = {}) => ['tariffs', params],
  tariff: (tariffId) => ['tariff', tariffId],
  siteSettings: ['siteSettings'],
  loggedUser: ['loggedUser'],
  histories: (params = {}) => ['histories', params],
  supportTickets: (params = {}) => ['supportTickets', params],
  supportTicket: (ticketId) => ['supportTicket', ticketId],
  supportSummary: ['supportSummary'],
  paymentHistory: (params = {}) => ['paymentHistory', params],
  paymentOperations: (params = {}) => ['paymentOperations', params],
}
