import { useEffect, useMemo, useState } from 'react'
import { Alert, Linking, Pressable, StyleSheet, Text, View } from 'react-native'
import { router, useLocalSearchParams } from 'expo-router'
import { MaterialCommunityIcons } from '@expo/vector-icons'
import { useQueryClient } from '@tanstack/react-query'
import type { Client, Event, Service } from '../../src/shared/domain/types'
import { formatPhoneForDisplay } from '../../src/shared/format/phone'
import { getCachedEntity, listCachedEntities } from '../../src/shared/storage/cache'
import { saveLocalEntity } from '../../src/shared/storage/mutations'
import { Button, EmptyState, PageHeader, Screen, SectionTitle, StatusChip, Surface } from '../../src/shared/ui/components'
import { colors, radius, spacing } from '../../src/shared/ui/theme'
import { buildEventNavigationLinks, formatEventAddress } from '../../src/features/events/navigation'
import { useWorkItemTerminology } from '../../src/shared/hooks/useWorkItemTerminology'

const statusLabel = { draft: 'Заявка', active: 'Подтверждено', canceled: 'Отменено', closed: 'Закрыто' }

export default function EventDetailScreen() {
  const terms = useWorkItemTerminology()
  const { id } = useLocalSearchParams<{ id: string }>()
  const queryClient = useQueryClient()
  const [event, setEvent] = useState<Event | null>(null)
  const [clients, setClients] = useState<Client[]>([])
  const [services, setServices] = useState<Service[]>([])
  useEffect(() => { if (id) Promise.all([getCachedEntity<Event>('events', id), listCachedEntities<Client>('clients'), listCachedEntities<Service>('services')]).then(([item, clientItems, serviceItems]) => { setEvent(item); setClients(clientItems); setServices(serviceItems) }) }, [id])
  const client = useMemo(() => clients.find((item) => item._id === event?.clientId), [clients, event?.clientId])
  const selectedServices = useMemo(() => services.filter((service) => event?.servicesIds?.includes(service._id)), [event?.servicesIds, services])
  const otherContacts = useMemo(() => (event?.otherContacts || []).map((contact) => ({
    ...contact,
    client: clients.find((item) => item._id === contact.clientId),
  })).filter((contact) => contact.client), [clients, event?.otherContacts])
  if (!event) return <Screen><PageHeader title={terms.labelCapitalized} /><EmptyState title="Запись не найдена" description="Возможно, она была удалена на другом устройстве." /></Screen>
  const toggleTask = async (index: number) => { const tasks = [...(event.additionalEvents || [])]; const task = tasks[index]; tasks[index] = { ...task, done: !task.done, doneAt: !task.done ? new Date().toISOString() : null }; const updated = await saveLocalEntity({ entityType: 'events', entityId: event._id, values: { additionalEvents: tasks } }); setEvent(updated as Event); await queryClient.invalidateQueries({ queryKey: ['cached-entities', 'events'] }) }
  const phone = String(client?.phone || '').replace(/\D/g, '')
  const addressText = formatEventAddress(event.address)
  const openNavigation = () => {
    const links = buildEventNavigationLinks(event.address)
    if (!links.length) return
    Alert.alert(`Маршрут к ${terms.dative}`, addressText, [
      ...links.map((link) => ({ text: link.title, onPress: () => Linking.openURL(link.url) })),
      { text: 'Отмена', style: 'cancel' as const },
    ])
  }
  const dateSubtitle = event.eventDate
    ? `${new Date(event.eventDate).toLocaleString('ru-RU')}${event.dateEnd ? ` — ${new Date(event.dateEnd).toLocaleString('ru-RU')}` : ''}`
    : 'Дата не назначена'
  const openMenu = () => Alert.alert('Действия', '', [
    { text: 'История действий', onPress: () => router.push({ pathname: '/history', params: { entityType: 'event', entityId: event._id } } as never) },
    { text: 'Отмена', style: 'cancel' },
  ])
  return <Screen><PageHeader title={event.eventType || terms.labelCapitalized} subtitle={dateSubtitle} action={<View style={styles.headerActions}><Pressable style={styles.edit} onPress={() => router.push(`/events/edit/${event._id}` as never)}><MaterialCommunityIcons name="pencil-outline" size={21} color={colors.primary} /></Pressable><Pressable style={styles.edit} onPress={openMenu}><MaterialCommunityIcons name="dots-vertical" size={22} color={colors.primary} /></Pressable></View>} /><View style={styles.statusRow}><StatusChip label={statusLabel[event.status]} tone={event.status === 'active' ? 'success' : event.status === 'draft' ? 'warning' : event.status === 'canceled' ? 'danger' : 'neutral'} />{event.syncStatus && event.syncStatus !== 'synced' ? <StatusChip label="Ожидает синхронизации" tone="blue" /> : null}</View>
    {client ? <Surface><View style={styles.client}><View style={styles.clientIcon}><MaterialCommunityIcons name="account-outline" size={23} color={colors.primary} /></View><View style={styles.grow}><Text style={styles.clientName}>{[client.firstName, client.secondName].filter(Boolean).join(' ') || 'Клиент'}</Text><Text style={styles.muted}>{formatPhoneForDisplay(client.phone) || client.email || ''}</Text></View>{phone ? <Pressable style={styles.roundButton} onPress={() => Linking.openURL(`tel:${phone}`)}><MaterialCommunityIcons name="phone-outline" size={21} color={colors.primary} /></Pressable> : null}<Pressable onPress={() => router.push(`/clients/${client._id}` as never)}><MaterialCommunityIcons name="chevron-right" size={24} color={colors.textMuted} /></Pressable></View></Surface> : null}
    <Surface><SectionTitle>Детали</SectionTitle>{event.description ? <Text style={styles.description}>{event.description}</Text> : null}{addressText ? <Pressable accessibilityRole="button" style={styles.address} onPress={openNavigation}><MaterialCommunityIcons name="map-marker-outline" size={20} color={colors.primary} /><Text style={styles.addressText}>{addressText}</Text><MaterialCommunityIcons name="navigation-variant-outline" size={21} color={colors.primary} /></Pressable> : null}<Info icon="cash" value={event.contractSum ? `Сумма договора: ${new Intl.NumberFormat('ru-RU').format(event.contractSum)} ₽` : ''} />{event.waitDeposit ? <View style={styles.deposit}><MaterialCommunityIcons name="alert-circle-outline" size={20} color={colors.warning} /><Text style={styles.depositText}>Ожидается задаток{event.depositExpectedAmount ? ` ${event.depositExpectedAmount} ₽` : ''}{event.depositDueAt ? ` до ${new Date(event.depositDueAt).toLocaleDateString('ru-RU')}` : ''}</Text></View> : null}</Surface>
    {selectedServices.length ? <Surface><SectionTitle>Услуги</SectionTitle>{selectedServices.map((service) => <View key={service._id} style={styles.service}><View style={styles.serviceIcon}><MaterialCommunityIcons name="star-outline" size={19} color={colors.primary} /></View><View style={styles.grow}><Text style={styles.serviceTitle}>{service.title || 'Услуга'}</Text>{service.description ? <Text style={styles.muted}>{service.description}</Text> : null}</View>{service.price ? <Text style={styles.servicePrice}>{new Intl.NumberFormat('ru-RU').format(service.price)} ₽</Text> : null}</View>)}</Surface> : null}
    {otherContacts.length ? <Surface><SectionTitle>Дополнительные контакты</SectionTitle>{otherContacts.map((contact, index) => { const contactPhone = String(contact.client?.phone || '').replace(/\D/g, ''); return <View key={`${contact.clientId}-${index}`} style={styles.client}><View style={styles.clientIcon}><MaterialCommunityIcons name="account-multiple-outline" size={22} color={colors.primary} /></View><View style={styles.grow}><Text style={styles.clientName}>{contact.client ? [contact.client.firstName, contact.client.secondName].filter(Boolean).join(' ') || 'Клиент' : 'Клиент'}</Text>{contact.comment ? <Text style={styles.muted}>{contact.comment}</Text> : null}</View>{contactPhone ? <Pressable style={styles.roundButton} onPress={() => Linking.openURL(`tel:${contactPhone}`)}><MaterialCommunityIcons name="phone-outline" size={21} color={colors.primary} /></Pressable> : null}{contact.client ? <Pressable style={styles.roundButton} onPress={() => router.push(`/clients/${contact.client?._id}` as never)}><MaterialCommunityIcons name="chevron-right" size={23} color={colors.textMuted} /></Pressable> : null}</View> })}</Surface> : null}
    <Surface><SectionTitle>Следующие контакты</SectionTitle>{event.additionalEvents?.length ? event.additionalEvents.map((task, index) => <Pressable key={task._id || index} style={styles.task} onPress={() => toggleTask(index)}><MaterialCommunityIcons name={task.done ? 'checkbox-marked-circle' : 'checkbox-blank-circle-outline'} size={23} color={task.done ? colors.success : colors.primary} /><View style={styles.grow}><Text style={[styles.taskTitle, task.done && styles.done]}>{task.title || 'Задача'}</Text><Text style={styles.muted}>{task.date ? new Date(task.date).toLocaleString('ru-RU') : 'Без срока'}</Text></View></Pressable>) : <Text style={styles.muted}>Нет запланированных контактов.</Text>}</Surface>
    <Button title="Добавить оплату или расход" onPress={() => router.push({ pathname: '/finance/edit/new', params: { eventId: event._id, clientId: event.clientId || '' } } as never)} disabled={event.status !== 'active'} /><Button title="Документы" variant="secondary" onPress={() => router.push(`/events/${event._id}/documents` as never)} /><Button title="Переписки Avito и VK" variant="secondary" onPress={() => router.push({ pathname: '/conversations', params: { eventId: event._id } } as never)} /><Button title="Позвонить клиенту" onPress={() => phone && Linking.openURL(`tel:${phone}`)} disabled={!phone} /><Button title="Клонировать" variant="secondary" onPress={() => Alert.alert('Клонирование', `Откройте редактор и сохраните копию ${terms.genitive}.`, [{ text: 'Отмена' }, { text: 'Создать копию', onPress: () => router.push({ pathname: '/events/edit/new', params: { cloneId: event._id } } as never) }])} />
  </Screen>
}
const Info = ({ icon, value }: { icon: keyof typeof MaterialCommunityIcons.glyphMap; value?: string }) => value ? <View style={styles.info}><MaterialCommunityIcons name={icon} size={19} color={colors.textMuted} /><Text style={styles.infoText}>{value}</Text></View> : null
const styles = StyleSheet.create({ headerActions: { flexDirection: 'row', gap: spacing.sm }, edit: { width: 44, height: 44, borderRadius: 22, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, statusRow: { flexDirection: 'row', gap: spacing.sm }, client: { flexDirection: 'row', alignItems: 'center', gap: spacing.md }, clientIcon: { width: 44, height: 44, borderRadius: 22, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, grow: { flex: 1 }, clientName: { color: colors.text, fontSize: 15, fontWeight: '700' }, muted: { color: colors.textMuted, fontSize: 12, marginTop: 3 }, roundButton: { width: 42, height: 42, borderRadius: 21, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, description: { color: colors.text, fontSize: 14, lineHeight: 21 }, info: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, infoText: { flex: 1, color: colors.textMuted, fontSize: 13 }, address: { minHeight: 52, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, padding: spacing.md, borderRadius: radius.md, backgroundColor: colors.primarySoft }, addressText: { flex: 1, color: colors.text, fontSize: 13, lineHeight: 19 }, deposit: { flexDirection: 'row', gap: spacing.sm, padding: spacing.md, backgroundColor: colors.warningSoft, borderRadius: radius.md }, depositText: { flex: 1, color: colors.warning, fontSize: 13, fontWeight: '700' }, task: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, paddingVertical: spacing.sm }, taskTitle: { color: colors.text, fontSize: 14, fontWeight: '700' }, done: { textDecorationLine: 'line-through', color: colors.textMuted }, service: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingVertical: spacing.xs }, serviceIcon: { width: 38, height: 38, borderRadius: 19, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, serviceTitle: { color: colors.text, fontSize: 14, fontWeight: '700' }, servicePrice: { color: colors.text, fontSize: 13, fontWeight: '700' } })
