import { draftMatches, initialDraft, jobStatuses, quoteDraft, readJob, readJobs, recordStatuses, safeImportError, safeJobProblem, shortageKopecks, validId, InvalidImportResponse } from './contract'
import { JOB_ID, OTHER_ID, makeJob, makeReview, makeQuoted, response, summary } from './fixtures'
it.each([undefined, null, [], [JOB_ID], '', ' ' + JOB_ID, JOB_ID + ' ', 'x'.repeat(24), 'abc'])('invalid ID %p не ремонтируется', (value) => expect(validId(value)).toBe(false))
it('ID сохраняет регистр; адресный ответ требует exact matching', () => { const id = 'Ab'.repeat(12); expect(readJob(response(makeJob({ id })), id).id).toBe(id); expect(() => readJob(response(makeJob({ id })), id.toLowerCase())).toThrow(InvalidImportResponse) })
it.each(jobStatuses)('принимает действительный статус %s', (status) => { const job = ['uploaded', 'analyzing', 'failed'].includes(status) ? makeJob({ status }) : makeReview({ status }); expect(readJob(response(job)).status).toBe(status) })
it.each(recordStatuses)('принимает статус записи %s', (status) => { const job = makeReview(); job.records[0].status = status; expect(readJob(response(job)).records[0].status).toBe(status) })
it.each([{}, { success: false, data: makeJob() }, { success: true }, { success: true, data: null }])('отклоняет invalid envelope %p', (raw) => expect(() => readJob(raw)).toThrow())
it.each([{ id: OTHER_ID }, { status: 'done' }, { balanceRub: NaN }, { refundPending: 'yes' }, { records: [{ id: '1', status: 'bad' }] }, { selectedIds: ['other'] }, { status: 'quoted' }, { quote: { ...makeJob().quote, id: ' ' + makeJob().quote!.id } }, { quote: { ...makeJob().quote, amountKopecks: 1.2 } }])('отклоняет invalid DTO %p', (patch) => expect(() => readJob(response(makeJob(patch as any)), JOB_ID)).toThrow())
it('список tenant jobs: shape, exact ID и отсутствие дублей', () => { expect(readJobs(response([summary()]))).toEqual([summary()]); expect(() => readJobs(response([summary(), summary()]))).toThrow(); expect(() => readJobs(response([{ ...summary(), id: [JOB_ID] }]))).toThrow(); expect(() => readJobs(response({ jobs: [] }))).toThrow() })
it('рубли/копейки: ровный баланс проходит, копейка нехватки не проходит', () => { expect(shortageKopecks(makeJob())).toBe(0); expect(shortageKopecks(makeJob({ balanceRub: 1.04 }))).toBe(1); expect(shortageKopecks(makeJob({ balanceRub: -1 }))).toBe(205) })
it('личный ключ не зависит от баланса, estimate сохраняется', () => { const j = makeJob({ balanceRub: 0, quote: { ...makeJob().quote!, provider: 'aitunnel', amountKopecks: 0 } }); expect(shortageKopecks(j)).toBe(0); expect(readJob(response(j)).quote?.estimatedKopecks).toBe(105) })
it('выбор исключает созданные/duplicate, comment и required ответы', () => { const j = makeReview(); j.records.push({ ...j.records[0], id: '2', status: 'created' }, { ...j.records[0], id: '3', status: 'duplicate' }); j.selectedIds = ['1', '2', '3']; expect(initialDraft(j).selectedIds).toEqual(['1']); expect(() => quoteDraft(j, initialDraft(j))).toThrow(); expect(quoteDraft(j, { answers: { q1: ' 2026 ', comment: ' правило ' }, selectedIds: ['3', '2', '1'] })).toEqual({ answers: { q1: '2026', comment: 'правило' }, selectedIds: ['1'] }) })
it('сравнение draft не зависит от порядка, не исправляет ID', () => { expect(draftMatches(initialDraft(makeQuoted()), { answers: { comment: '', q1: '2026' }, selectedIds: ['1'] })).toBe(true); expect(draftMatches(initialDraft(makeQuoted()), { answers: { q1: '2026' }, selectedIds: [' 1'] })).toBe(false) })
it.each(['QUOTE_CHANGED', 'AI_UNAVAILABLE', 'IMPORT_EXPIRED', 'AI_ACCESS_REQUIRED', 'INSUFFICIENT_BALANCE'])('безопасный текст %s без сырого error/source', (code) => { expect(safeImportError({ code, message: 'SECRET SOURCE PII' })).not.toMatch(/SECRET|SOURCE|PII/); expect(safeImportError({ code })).not.toBe(safeImportError(new Error('raw'))) })

it('реальная известная ошибка показывается, сырая provider ошибка заменяется', () => { const message = 'Достигнут согласованный предел расходов. Рассчитайте стоимость оставшихся записей.'; expect(safeJobProblem(message, 'fallback')).toBe(message); expect(safeJobProblem('provider SECRET source PII', 'fallback')).toBe('fallback'); expect(safeImportError({ status: 402 })).toMatch(/Недостаточно средств/) })
