import { api } from '../../shared/api/client'
import { changeJob, checkEvent, getJob, listJobs, uploadJob } from './fileImportApi'
import { EVENT_ID, JOB_ID, OTHER_ID, QUOTE_ID, makeJob, response, summary } from './fixtures'
jest.mock('../../shared/api/client', () => ({ api: { get: jest.fn(), post: jest.fn(), upload: jest.fn() } }))
beforeEach(() => jest.resetAllMocks())
it('list и адресный GET используют существующий bearer client без worker', async () => { (api.get as jest.Mock).mockResolvedValueOnce(response([summary()])).mockResolvedValueOnce(response(makeJob())); await listJobs(); await getJob(JOB_ID); expect(api.get).toHaveBeenNthCalledWith(1, '/events/file-import'); expect(api.get).toHaveBeenNthCalledWith(2, `/events/file-import?id=${JOB_ID}`) })
it.each([[], [JOB_ID], ' ' + JOB_ID, OTHER_ID.slice(1)])('invalid ID %p не вызывает сети', async (id) => { await expect(getJob(id as any)).rejects.toThrow(); await expect(changeJob(id as any, 'start')).rejects.toThrow(); await expect(checkEvent(id as any)).rejects.toThrow(); expect(api.get).not.toHaveBeenCalled(); expect(api.post).not.toHaveBeenCalled() })
it('paid POST exact quote, skipRefresh запрет повтора, exact GET/POST job', async () => { (api.post as jest.Mock).mockResolvedValue(response(makeJob())); await changeJob(JOB_ID, 'analyze', { quoteId: QUOTE_ID }); expect(api.post).toHaveBeenCalledWith(`/events/file-import/${JOB_ID}`, { action: 'analyze', quoteId: QUOTE_ID }, { skipRefresh: true }); (api.post as jest.Mock).mockResolvedValue(response(makeJob({ id: OTHER_ID }))); await expect(changeJob(JOB_ID, 'start')).rejects.toThrow(); (api.get as jest.Mock).mockResolvedValue(response(makeJob({ id: OTHER_ID }))); await expect(getJob(JOB_ID)).rejects.toThrow() })
it('multipart native file uri/name/type, reused и отсутствие auth payload', async () => { (api.upload as jest.Mock).mockResolvedValue({ ...response(makeJob()), reused: true }); const append = jest.spyOn(FormData.prototype, 'append'); const file = { uri: 'file:///cache/own.csv', name: 'файл.csv', type: 'text/csv' }; expect((await uploadJob(file, 'пояснение')).reused).toBe(true); expect(append).toHaveBeenCalledWith('file', file); expect(append).toHaveBeenCalledWith('note', 'пояснение'); expect(api.upload).toHaveBeenCalledWith('/events/file-import', expect.any(FormData)); expect(api.post).not.toHaveBeenCalled(); append.mockRestore() })
it.each([null, { _id: OTHER_ID }, { _id: EVENT_ID, deleted: true }, { _id: EVENT_ID, deletedAt: 'date' }])('нет открытия чужой/deleted/missing event %p', async (data) => { (api.get as jest.Mock).mockResolvedValue(response(data)); await expect(checkEvent(EVENT_ID)).rejects.toThrow() })
it('доступная event принимает только original ID', async () => { (api.get as jest.Mock).mockResolvedValue(response({ _id: EVENT_ID })); expect(await checkEvent(EVENT_ID)).toBe(EVENT_ID) })
it('false success и invalid reused отклоняются', async () => { (api.upload as jest.Mock).mockResolvedValue({ success: false, error: 'secret', code: 'AI_UNAVAILABLE' }); await expect(uploadJob({ uri: 'file:///x', name: 'x.csv', type: 'text/csv' }, '')).rejects.toThrow(); (api.upload as jest.Mock).mockResolvedValue({ ...response(makeJob()), reused: 'yes' }); await expect(uploadJob({ uri: 'file:///x', name: 'x.csv', type: 'text/csv' }, '')).rejects.toThrow() })
