import React from 'react'
import { act, fireEvent, render, waitFor } from '@testing-library/react-native'
import { Alert, StyleSheet } from 'react-native'
import ImportRoute from '../../../app/more/import'
import { ThemeProvider } from '../../shared/ui/ThemeProvider'
import { darkPalette, lightPalette } from '../../shared/ui/theme'
import { EVENT_ID, JOB_ID, OTHER_ID, NEW_QUOTE_ID, makeJob, makeReview, makeQuoted, response, summary, deferred } from './fixtures'
jest.setTimeout(20000)
const mockGet = jest.fn(), mockPost = jest.fn(), mockUpload = jest.fn(), mockPicker = jest.fn(), mockSync = jest.fn(), mockInvalidate = jest.fn(), mockCached = jest.fn(), mockPush = jest.fn(), mockOnline = jest.fn(), mockSyncState = jest.fn(), mockCleanup = jest.fn(), mockDispatch = jest.fn()
let mockFocus = true, mockParams: Record<string, unknown> = {}, mockUser: any = { _id: '1'.repeat(24), tenantId: 'tenant' }
let mockBeforeRemove: (event: any) => void
const mockNav = { addListener: jest.fn((_event: string, callback: any) => { mockBeforeRemove = callback; return () => undefined }), dispatch: (...args: any[]) => mockDispatch(...args) }
const mockQuery = { invalidateQueries: (...args: any[]) => mockInvalidate(...args) }
jest.mock('expo-router', () => ({ router: { push: (...args: any[]) => mockPush(...args) }, useLocalSearchParams: () => mockParams, useNavigation: () => mockNav, useFocusEffect: (fn: any) => require('react').useEffect(() => mockFocus ? fn() : undefined, [fn, mockFocus]) }))
jest.mock('@tanstack/react-query', () => ({ useQueryClient: () => mockQuery }))
jest.mock('../../shared/auth/AuthProvider', () => ({ useAuth: () => ({ user: mockUser }) }))
jest.mock('../../shared/hooks/useWorkItemTerminology', () => ({ useWorkItemTerminology: () => ({ pluralGenitive: 'заказов' }) }))
jest.mock('../../shared/api/client', () => ({ api: { get: (...args: any[]) => mockGet(...args), post: (...args: any[]) => mockPost(...args), upload: (...args: any[]) => mockUpload(...args) } }))
jest.mock('../../shared/sync/syncEngine', () => ({ runSync: (...args: any[]) => mockSync(...args) }))
jest.mock('../../shared/sync/syncState', () => ({ getSyncRunState: () => mockSyncState() }))
jest.mock('../../shared/storage/cache', () => ({ getCachedEntity: (...args: any[]) => mockCached(...args) }))
jest.mock('./nativeFile', () => ({ pickImportFile: (...args: any[]) => mockPicker(...args) }))
jest.mock('@react-native-community/netinfo', () => ({ fetch: () => mockOnline() }))
jest.mock('@expo/vector-icons', () => ({ MaterialCommunityIcons: () => null }))
jest.mock('react-native-safe-area-context', () => ({ SafeAreaView: require('react-native').View }))
const draw = (mode: 'light' | 'dark' = 'light') => <ThemeProvider forcedMode={mode} storage={null}><ImportRoute /></ThemeProvider>
const direct = (job = makeJob()) => { mockParams = { jobId: job.id }; mockGet.mockImplementation((path: string) => Promise.resolve(response(path === '/events/file-import' ? [summary(job)] : job))) }
const confirmLast = async () => { const calls = (Alert.alert as jest.Mock).mock.calls; const buttons = calls[calls.length - 1][2]; await act(async () => buttons[buttons.length - 1].onPress()) }
beforeEach(() => { jest.clearAllMocks(); mockFocus = true; mockParams = {}; mockUser = { _id: '1'.repeat(24), tenantId: 'tenant' }; mockGet.mockResolvedValue(response([])); mockOnline.mockResolvedValue({ isConnected: true, isInternetReachable: true }); mockSync.mockResolvedValue({}); mockSyncState.mockResolvedValue({ status: 'success', lastCompletedAt: 'now' }); mockCached.mockResolvedValue({ _id: EVENT_ID }); mockCleanup.mockReturnValue(true); mockPicker.mockResolvedValue({ uri: 'file:///cache/own.csv', name: 'файл.csv', type: 'text/csv', size: 12, cleanup: mockCleanup }); jest.spyOn(Alert, 'alert').mockImplementation(() => undefined) })
afterEach(() => jest.restoreAllMocks())
it.each(['light', 'dark'] as const)('native route %s / long names / theme / no fictional Google-export buttons', async (mode) => {
  const longName = 'Очень длинное название файла '.repeat(12) + '.csv'; mockGet.mockResolvedValue(response([summary(makeJob({ fileName: longName }))])); const screen = render(draw(mode)); await screen.findByText(longName + ' · Файл загружен')
  const title = screen.getByText('Импорт и экспорт'); expect(StyleSheet.flatten(title.props.style).color).toBe((mode === 'dark' ? darkPalette : lightPalette).text)
  expect(screen.getByText(/Отдельный Google-импорт пока доступен только/)).toBeTruthy(); expect(screen.getByRole('button', { name: 'Открыть общий экспорт' })).toBeTruthy(); expect(screen.getByLabelText('Этапы импорта')).toBeTruthy(); screen.unmount()
})
it('loading/empty/error/retry без ложного пустого успеха', async () => { const pending = deferred<unknown>(); mockGet.mockReturnValueOnce(pending.promise); const screen = render(draw()); expect(screen.getByLabelText('Запрос импорта')).toBeTruthy(); expect(screen.queryByText('Сохранённых импортов пока нет')).toBeNull(); await act(async () => pending.reject(new Error('SECRET PII'))); expect(screen.queryByText('SECRET PII')).toBeNull(); fireEvent.press(screen.getByText('Обновить список импортов')); await screen.findByText('Сохранённых импортов пока нет'); screen.unmount() })
it('403 показывает тариф и закрывает picker; личный ключ не обход', async () => { mockGet.mockRejectedValue({ status: 403, message: 'SECRET' }); const screen = render(draw()); await screen.findAllByText(/нужен действующий тариф с ИИ/); fireEvent.press(screen.getByText('Выбрать файл')); expect(mockPicker).not.toHaveBeenCalled(); expect(screen.queryByText('Сохранённых импортов пока нет')).toBeNull(); screen.unmount() })
it.each([[], [JOB_ID], ' ' + JOB_ID, 'bad'])('invalid/array route %p вообще не запрашивает jobs', (jobId) => { mockParams = { jobId }; const screen = render(draw()); expect(screen.getByText(/Некорректный адрес/)).toBeTruthy(); expect(mockGet).not.toHaveBeenCalled(); screen.unmount() })
it('upload native multipart/reused бесплатно открывает job; цена не запускается автоматически', async () => { mockUpload.mockResolvedValue({ ...response(makeJob()), reused: true }); const screen = render(draw()); await screen.findByText('Сохранённых импортов пока нет'); fireEvent.press(screen.getByText('Выбрать файл')); await screen.findByText('файл.csv · 12 байт'); mockGet.mockResolvedValueOnce(response(makeJob())); fireEvent.press(screen.getByText('Загрузить и проверить бесплатно')); await screen.findByText(/Открыт ранее сохранённый/); expect(mockUpload).toHaveBeenCalledWith('/events/file-import', expect.any(FormData)); expect(mockCleanup).toHaveBeenCalled(); expect(mockPost).not.toHaveBeenCalled(); screen.unmount() })
it('личный ключ показывает внешние расходы/estimate/модель и отдельный Alert', async () => { direct(makeJob({ balanceRub: 0, quote: { ...makeJob().quote!, provider: 'aitunnel', amountKopecks: 0 } })); const screen = render(draw()); await screen.findByText('Подтвердить смету и анализ'); fireEvent.press(screen.getByText('Подтвердить смету и анализ')); expect(Alert.alert).toHaveBeenCalledWith('Подтвердить расходы?', expect.stringMatching(/расходы оплачиваются внешнему провайдеру/), expect.any(Array)); expect((Alert.alert as jest.Mock).mock.calls[0][1]).toMatch(/model-test.*1,05/); expect(mockPost).not.toHaveBeenCalled(); expect(screen.getByText(/Списано с баланса Ведело — анализ:/)).toBeTruthy(); expect(screen.queryByText(/Всего списано: 0/)).toBeNull(); screen.unmount() })
it('правки answers сохраняются при error; stale Alert после draft не запускает import', async () => { direct(makeQuoted()); const screen = render(draw()); await screen.findByText('Какой год?'); fireEvent.press(screen.getByText('Подтвердить смету и начать импорт')); fireEvent.changeText(screen.getByLabelText('Какой год?'), '2027'); await confirmLast(); expect(mockPost).not.toHaveBeenCalled(); mockPost.mockRejectedValue(new Error('network')); fireEvent.press(screen.getByText('Рассчитать импорт выбранных записей')); await waitFor(() => expect(mockPost).toHaveBeenCalledTimes(1)); expect(screen.getByLabelText('Какой год?').props.value).toBe('2027'); screen.unmount() })
it('reopen review показывает summary/rules/examples/ignored/source/warnings/выбор', async () => { const j = makeReview(); j.records[0].warnings = ['Проверьте время']; direct(j); const screen = render(draw()); await screen.findByText('Какой год?'); expect(screen.getByText('Правила заполнения: Каждая строка — работа')).toBeTruthy(); expect(screen.getByText('Строка → пример')).toBeTruthy(); expect(screen.getByText('Лист / L2: Общий заголовок')).toBeTruthy(); fireEvent.press(screen.getByLabelText('Источник: Первая запись')); expect(screen.getByText('Лист / L1: исходник')).toBeTruthy(); expect(screen.getByText('Проверьте время')).toBeTruthy(); fireEvent.press(screen.getByLabelText('Импортировать: Первая запись')); expect(screen.getByText(/Выбрано записей: 0/)).toBeTruthy(); fireEvent.press(screen.getByText('Рассчитать импорт выбранных записей')); await screen.findByText(/Ответьте на все уточнения/); expect(mockPost).not.toHaveBeenCalled(); screen.unmount() })
it('явный quote read-back затем start с точным ID; подтверждение два раза один POST', async () => { direct(makeReview()); const screen = render(draw()); await screen.findByText('Какой год?'); fireEvent.changeText(screen.getByLabelText('Какой год?'), '2026'); mockPost.mockResolvedValue(response(makeQuoted())); mockGet.mockResolvedValueOnce(response(makeQuoted())); fireEvent.press(screen.getByText('Рассчитать импорт выбранных записей')); await screen.findByText(/Новая смета прочитана/); fireEvent.press(screen.getByText('Подтвердить смету и начать импорт')); const buttons = (Alert.alert as jest.Mock).mock.calls.at(-1)[2]; mockPost.mockResolvedValue(response(makeQuoted({ status: 'importing' }))); mockGet.mockResolvedValueOnce(response(makeQuoted({ status: 'importing' }))); await act(async () => { buttons[1].onPress(); buttons[1].onPress() }); await screen.findByText(/Сервер принял запуск/); expect(mockPost).toHaveBeenCalledTimes(2); expect(mockPost.mock.calls[1]).toEqual([`/events/file-import/${JOB_ID}`, { action: 'start', quoteId: NEW_QUOTE_ID }, { skipRefresh: true }]); screen.unmount() })
it('Back и смена job требуют предупреждение о draft, отмена сохраняет его', async () => { direct(makeQuoted()); const screen = render(draw()); await screen.findByText('Какой год?'); fireEvent.changeText(screen.getByLabelText('Какой год?'), '2030'); const preventDefault = jest.fn(); act(() => mockBeforeRemove({ preventDefault, data: { action: { type: 'BACK' } } })); expect(preventDefault).toHaveBeenCalled(); expect(Alert.alert).toHaveBeenCalledWith('Несохранённые изменения', expect.any(String), expect.any(Array)); expect(screen.getByLabelText('Какой год?').props.value).toBe('2030'); fireEvent.press(screen.getByText('Другой файл')); expect((Alert.alert as jest.Mock).mock.calls.at(-1)[1]).toContain('Сменить импорт'); await confirmLast(); await screen.findByText('Выбрать файл'); screen.unmount() })
it('выбор сохранённого job после discard работает, без смешивания answers', async () => { const j = makeQuoted(); direct(j); mockGet.mockImplementation((path: string) => Promise.resolve(response(path === '/events/file-import' ? [summary(j), summary(makeJob({ id: OTHER_ID }))] : path.includes(OTHER_ID) ? makeJob({ id: OTHER_ID, fileName: 'other.csv' }) : j))); const screen = render(draw()); await screen.findByText('Какой год?'); fireEvent.changeText(screen.getByLabelText('Какой год?'), '2030'); fireEvent.press(screen.getByText('Длинное имя файла.csv · Файл загружен')); await confirmLast(); await screen.findByText('other.csv'); expect(screen.queryByLabelText('Какой год?')).toBeNull(); screen.unmount() })
it('blur/profile late upload не делает GET/sync/navigation и чистит исходник', async () => { const screen = render(draw()); await screen.findByText('Сохранённых импортов пока нет'); fireEvent.press(screen.getByText('Выбрать файл')); await screen.findByText('файл.csv · 12 байт'); const pending = deferred<unknown>(); mockUpload.mockReturnValueOnce(pending.promise); fireEvent.press(screen.getByText('Загрузить и проверить бесплатно')); await waitFor(() => expect(mockUpload).toHaveBeenCalledTimes(1)); const count = mockGet.mock.calls.length; mockFocus = false; screen.rerender(draw()); await act(async () => pending.resolve(response(makeJob()))); expect(mockGet).toHaveBeenCalledTimes(count); expect(mockSync).not.toHaveBeenCalled(); expect(mockPush).not.toHaveBeenCalled(); expect(mockCleanup).toHaveBeenCalled(); screen.unmount() })
it('profile replacement скрывает jobs/draft и устаревшее подтверждение', async () => { direct(makeQuoted()); const screen = render(draw()); await screen.findByText('Какой год?'); fireEvent.press(screen.getByText('Подтвердить смету и начать импорт')); mockUser = { _id: '2'.repeat(24), tenantId: 'other' }; mockParams = {}; mockGet.mockResolvedValue(response([])); screen.rerender(draw()); await screen.findByText('Сохранённых импортов пока нет'); await confirmLast(); expect(mockPost).not.toHaveBeenCalled(); expect(screen.queryByLabelText('Какой год?')).toBeNull(); screen.unmount() })
it('completed со skipped/errors честен, sync fail retry не повторяет start', async () => { const j = makeQuoted({ status: 'completed' }); j.records[0] = { ...j.records[0], status: 'needs_attention', error: 'SECRET PII' }; direct(j); mockSync.mockRejectedValueOnce(new Error('network')); const screen = render(draw()); await screen.findByText('Повторить синхронизацию'); expect(screen.queryByText('Все импортировано')).toBeNull(); expect(screen.getByText(/Проверьте созданные черновики/)).toBeTruthy(); expect(screen.getByText('Нужно уточнение: 1')).toBeTruthy(); fireEvent.press(screen.getByText('Повторить синхронизацию')); await screen.findByText(/Локальная синхронизация выполнена/); expect(mockSync).toHaveBeenCalledTimes(2); expect(mockPost).not.toHaveBeenCalled(); expect(mockInvalidate).toHaveBeenCalledWith({ queryKey: ['cached-entities', 'events'] }); expect(mockInvalidate).toHaveBeenCalledWith({ queryKey: ['cached-entities', 'clients'] }); screen.unmount() })
it('runSync offline return не выдаётся за выполненную синхронизацию', async () => { direct(makeQuoted({ status: 'completed' })); mockSyncState.mockResolvedValue({ status: 'offline', lastCompletedAt: 'yesterday' }); const screen = render(draw()); await screen.findByText('Повторить синхронизацию'); expect(mockInvalidate).not.toHaveBeenCalled(); screen.unmount() })
it.each([null, { _id: OTHER_ID }, { _id: EVENT_ID, deleted: true }])('foreign/missing/deleted %p не открываются после cached entry', async (data) => { const j = makeQuoted({ status: 'completed' }); j.records[0] = { ...j.records[0], status: 'created', eventId: EVENT_ID }; direct(j); const screen = render(draw()); await screen.findByText('Первая запись'); fireEvent.press(screen.getByLabelText('Источник: Первая запись')); mockGet.mockResolvedValueOnce(response(data)); fireEvent.press(screen.getByText('Открыть карточку для проверки')); await waitFor(() => expect(mockGet.mock.calls.at(-1)[0]).toBe(`/events/${EVENT_ID}`)); expect(mockPush).not.toHaveBeenCalled(); screen.unmount() })
it('original created event открывается только после sync, local availability и exact remote read', async () => { const j = makeQuoted({ status: 'completed' }); j.records[0] = { ...j.records[0], status: 'created', eventId: EVENT_ID }; direct(j); const screen = render(draw()); await screen.findByText('Первая запись'); fireEvent.press(screen.getByLabelText('Источник: Первая запись')); mockGet.mockResolvedValue(response({ _id: EVENT_ID })); fireEvent.press(screen.getByText('Открыть карточку для проверки')); await waitFor(() => expect(mockPush).toHaveBeenCalledWith(`/events/edit/${EVENT_ID}`)); expect(mockCached).toHaveBeenCalledWith('events', EVENT_ID); expect(mockGet.mock.calls.filter(([path]) => path === `/events/${EVENT_ID}`)).toHaveLength(2); screen.unmount() })
it('missing local cache после pull блокирует navigation', async () => { const j = makeQuoted({ status: 'completed' }); j.records[0] = { ...j.records[0], status: 'created', eventId: EVENT_ID }; direct(j); const screen = render(draw()); await screen.findByText('Первая запись'); fireEvent.press(screen.getByLabelText('Источник: Первая запись')); mockCached.mockResolvedValue(null); mockGet.mockResolvedValue(response({ _id: EVENT_ID })); fireEvent.press(screen.getByText('Открыть карточку для проверки')); await waitFor(() => expect(mockCached).toHaveBeenCalled()); expect(mockPush).not.toHaveBeenCalled(); screen.unmount() })
it('смена route с dirty отвечает отменой без GET чужого job и без потери ответов', async () => { direct(makeQuoted()); const screen = render(draw()); await screen.findByText('Какой год?'); fireEvent.changeText(screen.getByLabelText('Какой год?'), '2029'); mockParams = { jobId: OTHER_ID }; screen.rerender(draw()); expect(Alert.alert).toHaveBeenCalled(); const buttons = (Alert.alert as jest.Mock).mock.calls.at(-1)[2]; await act(async () => buttons[0].onPress()); expect(screen.getByLabelText('Какой год?').props.value).toBe('2029'); expect(mockGet.mock.calls.some(([path]) => path.includes(OTHER_ID))).toBe(false); screen.unmount() })
it('late Back confirmation после profile replacement не dispatch новую navigation', async () => { direct(makeQuoted()); const screen = render(draw()); await screen.findByText('Какой год?'); fireEvent.changeText(screen.getByLabelText('Какой год?'), '2030'); act(() => mockBeforeRemove({ preventDefault: jest.fn(), data: { action: { type: 'BACK' } } })); const old = (Alert.alert as jest.Mock).mock.calls.at(-1)[2][1]; mockUser = { _id: '2'.repeat(24), tenantId: 'other' }; mockParams = {}; mockGet.mockResolvedValue(response([])); screen.rerender(draw()); await screen.findByText('Сохранённых импортов пока нет'); await act(async () => old.onPress()); expect(mockDispatch).not.toHaveBeenCalled(); screen.unmount() })
