import { ImportController, type ImportDependencies, type RequestGate } from './ImportController'
import { EVENT_ID, JOB_ID, OTHER_ID, makeJob, makeReview, makeQuoted, summary, deferred } from './fixtures'
import type { Job } from './contract'
const flush = async () => { for (let i = 0; i < 20; i++) await Promise.resolve() }
function setup(job = makeJob(), gate?: RequestGate) {
  const cleanup = jest.fn(() => true), file = { uri: 'file:///cache/own.csv', name: 'own.csv', type: 'text/csv', size: 12, cleanup }
  const deps: jest.Mocked<ImportDependencies> = { list: jest.fn().mockResolvedValue([summary(job)]), get: jest.fn().mockResolvedValue(job), change: jest.fn().mockResolvedValue(job), upload: jest.fn().mockResolvedValue({ job, reused: false }), pick: jest.fn().mockResolvedValue(file), online: jest.fn().mockResolvedValue(true), sync: jest.fn().mockResolvedValue(undefined), event: jest.fn().mockResolvedValue(EVENT_ID), navigate: jest.fn() }
  return { c: new ImportController(deps, gate), deps, cleanup, file }
}
beforeEach(() => jest.useFakeTimers())
afterEach(() => jest.useRealTimers())
it('свои jobs открываются и бесплатный upload ничего платного не делает', async () => { const { c, deps, cleanup } = setup(); c.focus(); await flush(); expect(c.state.jobs).toEqual([summary()]); await c.pick(); c.setNote('Общий год'); await c.upload(); expect(deps.upload).toHaveBeenCalledWith(expect.objectContaining({ name: 'own.csv' }), 'Общий год'); expect(deps.get).toHaveBeenCalledWith(JOB_ID); expect(deps.change).not.toHaveBeenCalled(); expect(cleanup).toHaveBeenCalled(); expect(c.state.needsRead).toBe(false); c.blur() })
it('reused upload/reopen принимает реальное состояние сохранённого job', async () => { const job = makeQuoted(); const { c, deps } = setup(job); deps.upload.mockResolvedValue({ job, reused: true }); c.focus(); await flush(); await c.pick(); await c.upload(); expect(c.state.notice).toContain('ранее'); expect(c.state.draft.answers.q1).toBe('2026'); expect(c.confirmation('start')).not.toBeNull(); c.blur(); c.focus(); await flush(); expect(c.state.job?.id).toBe(JOB_ID); c.blur() })
it.each(['bad', ' ' + JOB_ID])('invalid direct id %s не вызывает GET/list', async (id) => { const { c, deps } = setup(); c.focus(id); await flush(); expect(deps.get).not.toHaveBeenCalled(); expect(deps.list).not.toHaveBeenCalled(); expect(c.state.error).toContain('Некорректный'); c.blur() })
it('failed open сохраняет exact target для повторного GET', async () => { const { c, deps } = setup(); deps.get.mockRejectedValueOnce(new Error('network')); c.focus(JOB_ID); await flush(); expect(c.state.job).toBeNull(); await c.read(); expect(deps.get).toHaveBeenNthCalledWith(2, JOB_ID); expect(c.state.job?.id).toBe(JOB_ID); c.blur() })
it('explicit current quote, двойное подтверждение делает один analyze', async () => { const { c, deps } = setup(); c.focus(JOB_ID); await flush(); const confirm = c.confirmation('analyze')!; expect(deps.change).not.toHaveBeenCalled(); deps.change.mockResolvedValue(makeJob({ status: 'analyzing' })); deps.get.mockResolvedValue(makeJob({ status: 'analyzing' })); await Promise.all([c.confirm(confirm), c.confirm(confirm)]); expect(deps.change).toHaveBeenCalledTimes(1); expect(deps.change).toHaveBeenCalledWith(JOB_ID, 'analyze', { quoteId: makeJob().quote!.id }); expect(c.state.job?.status).toBe('analyzing'); c.blur() })
it.each([1.04, 0])('нехватка баланса %s блокирует paid confirmation', async (balanceRub) => { const { c } = setup(makeJob({ balanceRub })); c.focus(JOB_ID); await flush(); expect(c.confirmation('analyze')).toBeNull(); c.blur() })
it('ровный баланс и личный ключ с нулевым балансом допускают подтверждение', async () => { const { c } = setup(makeJob({ balanceRub: 0, quote: { ...makeJob().quote!, provider: 'aitunnel', amountKopecks: 0 } })); c.focus(JOB_ID); await flush(); expect(c.confirmation('analyze')).not.toBeNull(); c.blur() })
it('expired и неверная phase не запускаются', async () => { const { c } = setup(makeJob({ expiresAt: '2000-01-01T00:00:00Z' })); c.focus(JOB_ID); await flush(); expect(c.confirmation('analyze')).toBeNull(); c.blur(); const b = setup(makeJob({ quote: { ...makeJob().quote!, phase: 'import' } })); b.c.focus(JOB_ID); await flush(); expect(b.c.confirmation('analyze')).toBeNull(); b.c.blur() })
it('quote требует ответы и selection, бесплатен; reset draft только после read-back', async () => { const { c, deps } = setup(makeReview()); c.focus(JOB_ID); await flush(); await c.quote(); expect(deps.change).not.toHaveBeenCalled(); c.setAnswer('q1', '2026'); c.setAnswer('comment', ' Общее правило '); deps.change.mockResolvedValue(makeQuoted({ answers: { q1: '2026', comment: 'Общее правило' } })); deps.get.mockResolvedValue(makeQuoted({ answers: { q1: '2026', comment: 'Общее правило' } })); await c.quote(); expect(deps.change).toHaveBeenCalledWith(JOB_ID, 'quote', { answers: { q1: '2026', comment: 'Общее правило' }, selectedIds: ['1'] }); expect(c.state.dirty).toBe(false); expect(c.confirmation('start')).not.toBeNull(); c.blur() })
it('изменение answers/selection аннулирует открытый confirmation и quote', async () => { const { c, deps } = setup(makeQuoted()); c.focus(JOB_ID); await flush(); const confirm = c.confirmation('start')!; c.setAnswer('q1', '2027'); expect(c.confirmation('start')).toBeNull(); await c.confirm(confirm); expect(deps.change).not.toHaveBeenCalled(); c.toggle('1'); await c.quote(); expect(deps.change).not.toHaveBeenCalled(); c.blur() })
it('read нового quote и job change аннулируют старый диалог', async () => { const { c, deps } = setup(); c.focus(JOB_ID); await flush(); const confirm = c.confirmation('analyze')!; await c.read(); await c.confirm(confirm); expect(deps.change).not.toHaveBeenCalled(); const second = c.confirmation('analyze')!; deps.get.mockResolvedValue(makeJob({ id: OTHER_ID })); await c.open(OTHER_ID); await c.confirm(second); expect(deps.change).not.toHaveBeenCalled(); c.blur() })
it('потеря paid ответа: один recovery GET, нет успеха этой попытки и autopaid retry', async () => { const { c, deps } = setup(); c.focus(JOB_ID); await flush(); deps.change.mockRejectedValue(new Error('NETWORK SECRET')); deps.get.mockResolvedValue(makeJob()); await c.confirm(c.confirmation('analyze')!); expect(deps.change).toHaveBeenCalledTimes(1); expect(c.state.needsRead).toBe(false); expect(c.state.requiresQuote).toBe(true); expect(c.state.notice).toContain('не доказывает'); expect(c.state.error).not.toContain('SECRET'); expect(c.confirmation('analyze')).toBeNull(); jest.advanceTimersByTime(30000); await flush(); expect(deps.change).toHaveBeenCalledTimes(1); c.blur() })
it('lost POST + failed recovery блокирует paid до exact GET и нового quote', async () => { const { c, deps } = setup(); c.focus(JOB_ID); await flush(); deps.change.mockRejectedValue(new Error('NETWORK')); deps.get.mockRejectedValue(new Error('network')); await c.confirm(c.confirmation('analyze')!); expect(c.state.needsRead).toBe(true); deps.get.mockResolvedValue(makeJob()); await c.read(); expect(c.state.needsRead).toBe(false); expect(c.confirmation('analyze')).toBeNull(); const refreshed = makeJob({ quote: { ...makeJob().quote!, id: '12345678-abcd-4321-8901-123456789def' } }); deps.change.mockResolvedValue(refreshed); deps.get.mockResolvedValue(refreshed); await c.refreshQuote(); expect(c.confirmation('analyze')).not.toBeNull(); c.blur() })
it('POST successful / read-back failed не повторяет mutation и не затирает draft', async () => { const { c, deps } = setup(makeReview()); c.focus(JOB_ID); await flush(); c.setAnswer('q1', '2028'); deps.change.mockResolvedValue(makeQuoted({ answers: { q1: '2028', comment: '' } })); deps.get.mockRejectedValue(new Error('network')); await c.quote(); expect(deps.change).toHaveBeenCalledTimes(1); expect(c.state.needsRead).toBe(true); expect(c.state.draft.answers.q1).toBe('2028'); expect(c.state.dirty).toBe(true); c.blur() })
it('несовпадение quote read-back не подтверждает запуск', async () => { const { c, deps } = setup(makeReview()); c.focus(JOB_ID); await flush(); c.setAnswer('q1', '2026'); deps.change.mockResolvedValue(makeQuoted()); deps.get.mockResolvedValue(makeQuoted({ answers: { q1: '2030' } })); await c.quote(); expect(c.state.needsRead).toBe(true); expect(c.confirmation('start')).toBeNull(); expect(c.state.draft.answers.q1).toBe('2026'); c.blur() })
it('poll single-flight только после ответа и не перекрывает POST', async () => { const { c, deps } = setup(makeJob({ status: 'analyzing' })); c.focus(JOB_ID); await flush(); const pending = deferred<Job>(); deps.get.mockReturnValueOnce(pending.promise); jest.advanceTimersByTime(4000); await flush(); const count = deps.get.mock.calls.length; jest.advanceTimersByTime(40000); await flush(); expect(deps.get).toHaveBeenCalledTimes(count); expect(c.confirmation('stop')).toBeNull(); pending.resolve(makeReview()); await flush(); jest.advanceTimersByTime(10000); await flush(); expect(deps.get).toHaveBeenCalledTimes(count); expect(deps.change).not.toHaveBeenCalled(); c.blur() })
it.each([new Error('network'), { status: 403 }, new Error('invalid DTO')])('poll error %p прекращает таймер до retry', async (error) => { const { c, deps } = setup(makeJob({ status: 'analyzing' })); c.focus(JOB_ID); await flush(); deps.get.mockRejectedValueOnce(error); jest.advanceTimersByTime(4000); await flush(); const calls = deps.get.mock.calls.length; jest.advanceTimersByTime(60000); await flush(); expect(deps.get).toHaveBeenCalledTimes(calls); expect(c.state.pollStopped).toBe(true); if ((error as any).status === 403) { expect(c.state.job).toBeNull(); expect(c.state.jobs).toEqual([]) } c.blur() })
it('stop лишь request: read-back active не выдаётся за остановку', async () => { const job = makeJob({ status: 'analyzing' }); const { c, deps } = setup(job); c.focus(JOB_ID); await flush(); await c.confirm(c.confirmation('stop')!); expect(c.state.job?.status).toBe('analyzing'); expect(c.state.stopRequested).toBe(true); expect(c.state.notice).toContain('Дождитесь'); expect(deps.change).toHaveBeenCalledWith(JOB_ID, 'stop', { quoteId: job.quote!.id }); c.blur() })
it('release требует отдельное подтверждение, read-back refundPending false; job не удаляется', async () => { const job = makeQuoted({ status: 'paused', refundPending: true, reservedRub: 1 }); const { c, deps } = setup(job); c.focus(JOB_ID); await flush(); const confirm = c.confirmation('release')!; deps.change.mockResolvedValue({ ...job, refundPending: false }); deps.get.mockResolvedValue({ ...job, refundPending: false }); await c.confirm(confirm); expect(c.state.job?.id).toBe(JOB_ID); expect(c.state.notice).toContain('Возврат'); expect(deps.change).toHaveBeenCalledTimes(1); c.blur() })
it('offline не пишет outbox и не выдаёт платный успех', async () => { const { c, deps } = setup(); c.focus(JOB_ID); await flush(); deps.online.mockResolvedValue(false); await c.confirm(c.confirmation('analyze')!); expect(deps.change).not.toHaveBeenCalled(); expect(c.state.error).toContain('сеть'); c.blur() })
it('blur позднего POST не запускает GET/sync/cache/navigation; снова focus читает', async () => { const { c, deps } = setup(); c.focus(JOB_ID); await flush(); const pending = deferred<Job>(); deps.change.mockReturnValueOnce(pending.promise); const run = c.confirm(c.confirmation('analyze')!); await flush(); const gets = deps.get.mock.calls.length; c.blur(); pending.resolve(makeJob({ status: 'analyzing' })); await run; expect(deps.get).toHaveBeenCalledTimes(gets); expect(deps.sync).not.toHaveBeenCalled(); expect(deps.navigate).not.toHaveBeenCalled(); c.focus(); await flush(); expect(deps.get).toHaveBeenCalledWith(JOB_ID); expect(c.confirmation('analyze')).toBeNull(); c.blur() })
it('смена session использует общую gate: old результат не изменяет новую форму', async () => { const gate: RequestGate = { owner: null }; const old = setup(makeJob(), gate); old.c.focus(JOB_ID); await flush(); const pending = deferred<Job>(); old.deps.change.mockReturnValueOnce(pending.promise); const run = old.c.confirm(old.c.confirmation('analyze')!); await flush(); old.c.blur(); const next = setup(makeJob({ id: OTHER_ID }), gate); next.c.focus(OTHER_ID); await flush(); expect(next.deps.get).not.toHaveBeenCalled(); pending.resolve(makeJob({ status: 'analyzing' })); await run; await flush(); expect(next.c.state.job?.id).toBe(OTHER_ID); expect(old.deps.sync).not.toHaveBeenCalled(); next.c.blur() })
it('late upload/GET/picker после blur чистятся без form или navigation side effects', async () => { const { c, deps, cleanup, file } = setup(); c.focus(); await flush(); const pending = deferred<typeof file | null>(); deps.pick.mockReturnValueOnce(pending.promise); const run = c.pick(); c.blur(); pending.resolve(file); await run; expect(cleanup).toHaveBeenCalled(); expect(c.state.file).toBeNull(); c.focus(); await flush(); await c.pick(); const upload = deferred<{ job: Job; reused: boolean }>(); deps.upload.mockReturnValueOnce(upload.promise); const uploading = c.upload(); await flush(); c.blur(); upload.resolve({ job: makeQuoted(), reused: true }); await uploading; expect(c.state.job).toBeNull(); expect(deps.get).not.toHaveBeenCalled(); expect(deps.sync).not.toHaveBeenCalled() })
it('double pick и replacement/unmount cleanup', async () => { const { c, deps, cleanup, file } = setup(); c.focus(); await flush(); const pending = deferred<typeof file | null>(); deps.pick.mockReturnValueOnce(pending.promise); const run = c.pick(); await c.pick(); expect(deps.pick).toHaveBeenCalledTimes(1); pending.resolve(file); await run; await c.pick(); expect(cleanup).toHaveBeenCalledTimes(1); c.blur(); expect(cleanup).toHaveBeenCalledTimes(2) })
it('draft при refresh/read не затирается, смена job без discard заблокирована', async () => { const { c, deps } = setup(makeQuoted()); c.focus(JOB_ID); await flush(); c.setAnswer('comment', 'Личная правка'); await c.read(); expect(c.state.draft.answers.comment).toBe('Личная правка'); const calls = deps.get.mock.calls.length; await c.open(OTHER_ID); expect(deps.get).toHaveBeenCalledTimes(calls); c.discardDraft(); deps.get.mockResolvedValue(makeJob({ id: OTHER_ID })); await c.open(OTHER_ID); expect(c.state.job?.id).toBe(OTHER_ID); c.blur() })
it('mixed completion/sync failed: retry sync без duplicate start, created исключены', async () => { const job = makeQuoted({ status: 'completed' }); job.records = [{ ...job.records[0], status: 'created', eventId: EVENT_ID }, { ...job.records[0], id: '2', status: 'needs_attention', error: 'date unknown' }]; job.selectedIds = ['1', '2']; const { c, deps } = setup(job); deps.sync.mockRejectedValueOnce(new Error('sync')); c.focus(JOB_ID); await flush(); expect(c.state.sync).toBe('failed'); expect(c.state.draft.selectedIds).toEqual(['2']); await c.retrySync(); expect(c.state.sync).toBe('done'); expect(deps.sync).toHaveBeenCalledTimes(2); expect(deps.change).not.toHaveBeenCalled(); c.blur() })
it.each(['missing', 'foreign', 'deleted'])('event %s refusal не открывает карточку', async () => { const job = makeQuoted({ status: 'completed' }); job.records[0] = { ...job.records[0], status: 'created', eventId: EVENT_ID }; const { c, deps } = setup(job); c.focus(JOB_ID); await flush(); deps.event.mockRejectedValue(new Error('unavailable')); await c.openEvent('1'); expect(deps.navigate).not.toHaveBeenCalled(); c.blur() })
it('created карточка проверяется дважды с sync и original id', async () => { const job = makeQuoted({ status: 'completed' }); job.records[0] = { ...job.records[0], status: 'created', eventId: EVENT_ID }; const { c, deps } = setup(job); c.focus(JOB_ID); await flush(); await c.openEvent('1'); expect(deps.event).toHaveBeenNthCalledWith(1, EVENT_ID); expect(deps.event).toHaveBeenNthCalledWith(2, EVENT_ID, true); expect(deps.navigate).toHaveBeenCalledWith(EVENT_ID); c.blur() })
it('offline/sync failed/late event never navigates', async () => { const job = makeQuoted({ status: 'completed' }); job.records[0] = { ...job.records[0], status: 'created', eventId: EVENT_ID }; const { c, deps } = setup(job); c.focus(JOB_ID); await flush(); deps.online.mockResolvedValueOnce(false); await c.openEvent('1'); expect(deps.event).not.toHaveBeenCalled(); deps.sync.mockRejectedValueOnce(new Error('sync')); await c.openEvent('1'); expect(deps.navigate).not.toHaveBeenCalled(); const pending = deferred<string>(); deps.event.mockReturnValueOnce(pending.promise); const run = c.openEvent('1'); await flush(); c.blur(); pending.resolve(EVENT_ID); await run; expect(deps.navigate).not.toHaveBeenCalled() })
it('ошибка чтения/невалидный ответ не оставляют разрешение старого платного quote', async () => { const { c, deps } = setup(); c.focus(JOB_ID); await flush(); const old = c.confirmation('analyze')!; deps.get.mockRejectedValue(new Error('invalid')); await c.read(); expect(c.confirmation('analyze')).toBeNull(); await c.confirm(old); expect(deps.change).not.toHaveBeenCalled(); c.blur() })
it('refresh требует именно новый ID quote, old receipt не разрешает paid retry', async () => { const { c } = setup(); c.focus(JOB_ID); await flush(); await c.refreshQuote(); expect(c.state.needsRead).toBe(true); expect(c.confirmation('analyze')).toBeNull(); c.blur() })
it('долгий initial GET после blur/job change не публикует source и sync', async () => { const { c, deps } = setup(makeQuoted({ status: 'completed' })); const pending = deferred<Job>(); deps.get.mockReturnValueOnce(pending.promise); c.focus(JOB_ID); await flush(); c.blur(); pending.resolve(makeQuoted({ status: 'completed' })); await flush(); expect(c.state.job).toBeNull(); expect(deps.sync).not.toHaveBeenCalled(); expect(deps.list).not.toHaveBeenCalled() })
it('failure cleanup остаётся warning после попытки upload', async () => { const { c, deps, file } = setup(); file.cleanup.mockReturnValue(false); c.focus(); await flush(); await c.pick(); deps.upload.mockRejectedValue(new Error('network')); await c.upload(); expect(c.state.file).toBeNull(); expect(c.state.cleanupError).toBe(true); c.blur() })
it('after stop/paused/quote/resume можно запросить новую остановку', async () => { const { c, deps } = setup(makeQuoted({ status: 'importing' })); c.focus(JOB_ID); await flush(); await c.confirm(c.confirmation('stop')!); deps.get.mockResolvedValue(makeQuoted({ status: 'paused' })); await c.read(); const next = makeQuoted({ quote: { ...makeQuoted().quote!, id: '12345678-abcd-4321-8901-123456789999' } }); deps.get.mockResolvedValue(next); deps.change.mockResolvedValue(next); await c.quote(); deps.get.mockResolvedValue({ ...next, status: 'importing' }); deps.change.mockResolvedValue({ ...next, status: 'importing' }); await c.confirm(c.confirmation('start')!); expect(c.state.stopRequested).toBe(false); expect(c.confirmation('stop')).not.toBeNull(); c.blur() })

it('повторный quote с прежним UUID не снимает запрет платного повтора', async () => { const { c } = setup(makeQuoted()); c.focus(JOB_ID); await flush(); c.setAnswer('comment', ''); await c.quote(); expect(c.state.needsRead).toBe(true); expect(c.confirmation('start')).toBeNull(); c.blur() })

it('карточка удалена после успешного sync: нет navigation и зависшего pending', async () => { const job = makeQuoted({ status: 'completed' }); job.records[0] = { ...job.records[0], status: 'created', eventId: EVENT_ID }; const { c, deps } = setup(job); c.focus(JOB_ID); await flush(); deps.event.mockResolvedValueOnce(EVENT_ID).mockRejectedValueOnce({ status: 404 }); await c.openEvent('1'); expect(c.state.sync).toBe('done'); expect(c.state.error).toMatch(/недоступны/); expect(deps.navigate).not.toHaveBeenCalled(); c.blur() })
